---
apiVersion: v1
kind: Namespace
metadata:
  name: lis-dev
  labels:
    app.kubernetes.io/part-of: rasteronelab-lis
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: lis-staging
  labels:
    app.kubernetes.io/part-of: rasteronelab-lis
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: lis-prod
  labels:
    app.kubernetes.io/part-of: rasteronelab-lis
    environment: production
