package com.rasteronelab.lis.core.domain.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("BaseEntity")
class BaseEntityTest {

    /**
     * Concrete subclass for testing the abstract BaseEntity.
     */
    static class TestEntity extends BaseEntity {
    }

    @Test
    @DisplayName("New entity should have an auto-generated UUID")
    void newEntity_shouldHaveAutoGeneratedUuid() {
        TestEntity entity = new TestEntity();

        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isInstanceOf(UUID.class);
    }

    @Test
    @DisplayName("New entity should have isDeleted = false by default")
    void newEntity_shouldHaveIsDeletedFalse() {
        TestEntity entity = new TestEntity();

        assertThat(entity.getIsDeleted()).isFalse();
    }

    @Test
    @DisplayName("softDelete should set isDeleted=true and populate deletedAt")
    void softDelete_shouldSetIsDeletedTrueAndDeletedAt() {
        TestEntity entity = new TestEntity();

        entity.softDelete("admin-user");

        assertThat(entity.getIsDeleted()).isTrue();
        assertThat(entity.getDeletedAt()).isNotNull();
        assertThat(entity.getUpdatedBy()).isEqualTo("admin-user");
    }

    @Test
    @DisplayName("Two new entities should have different UUIDs")
    void newEntities_shouldHaveDifferentUuids() {
        TestEntity entity1 = new TestEntity();
        TestEntity entity2 = new TestEntity();

        assertThat(entity1.getId()).isNotEqualTo(entity2.getId());
    }
}
